#local
spring:
  datasource:
    url: jdbc:mariadb://barcoder.ckvu6z6e9nqy.ap-northeast-2.rds.amazonaws.com:3306/barcoder?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: merlin
    password: merlinbarcoder
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB